### ISSUE TITLE
[authentication]: systray shows notification popup then immediatly closes it

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#101]
Example: install synaptic and open it (will do a screencast shortly).
The authentication popup window comes up and systray pops up a notification, which closes immediatly and therefore is unreadable.
I suggest to not have an additional notification popup (i cant remember that opening synaptic had triggered a notification before).

**Comment by star-buck** [comment]
Here is a still of the screencast shwoing policykit1-kde
![polkit-notify](https://cloud.githubusercontent.com/assets/840070/6992389/ef8873ec-daca-11e4-83db-194521615106.png)
Its quite annyoing, redundant in that case and has no real benefit:
https://www.dropbox.com/s/68cexzuy1v3iq1w/synaptic-notification-popup.mkv?dl=0

**Comment by star-buck** [comment]
anything to fix this?

**Comment by davidedmundson** [comment]
Applying this will fix it. https://git.reviewboard.kde.org/r/123294/

It didnt go in because Martin G was aruging over a thing. I'll persuade him I'm right and get it into 5.3.1

**Comment by star-buck** [comment]
if we can apply this fix, its fine, enought time then for a proper fix for p5.3.1 or later.

**Comment by star-buck** [comment]
@apachelogger : can we ship this under ci-fixes?

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-fixes/+sourcepub/5052834/+listing-archive-extra

**Comment by star-buck** [comment]
seems fixed.

**Comment by star-buck** [comment]
this is still not fixed in 5.3.2:
it gets worse as it interferes with the "&&" parameter, example in Arch:
* sudo systemctl start smbd && systemctl start nmbd 

this asks for sudo-password in konsole and then immediatly pops up the plasma window to ask for another confirmation without closing it, while in konsole it repots already "Access Denied" for the second call.
If you execute both orders subsequently, everything goes fine.
Lets please kill that annyoing popup for good.

**Comment by davidedmundson** [comment]
Merged into 5.4 proper

**Comment by star-buck** [comment]
seems fixed
