### ISSUE TITLE
[kdenlive]: freezes when opening "Save" dialog

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#107]
Render Dialog works fine, but whenever trying to save, the dialog opens but one cannot enter anything in the field, kdenlive seems completely frozen.

**Comment by jurgen-74** [comment]
Yup, I've got the same problem. I have to downgrade to 9 else I cannot save my work :(

**Comment by star-buck** [comment]
still not fixed: https://bugs.kde.org/show_bug.cgi?id=346413#c10

**Comment by star-buck** [comment]
seems fixed

**Comment by asdf23** [comment]
grumble
