### ISSUE TITLE
[oxygen widget style]: missing shadows in dolphin4 dropdown menus

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#109]
![dolphin-shadows](https://cloud.githubusercontent.com/assets/840070/7445383/952a97ac-f1b0-11e4-8e2f-61c31a886a38.png)
![dolphin-shadows1](https://cloud.githubusercontent.com/assets/840070/7445384/952d45b0-f1b0-11e4-9d7e-751e8ab7cf7e.png)

**Comment by star-buck** [comment]
still no shadows in dolphin4 for dropdown or context menus when using oxygen widget style. 
@notmart: since d_ed and mgraessllin work on the phone, can you have a look?

**Comment by notmart** [comment]
ok, i can take a look at it.
@davidedmundson looks like the same issue solved for breeze by https://git.reviewboard.kde.org/r/123284/  ?
I can port the same thing to oxygen kde4

**Comment by notmart** [comment]
hmm, kde4 version of oxygen never checked for the supported atom, any other idea of what could be?
(note i correctly get shadows in dolphin with oxygen kde4 here)

**Comment by star-buck** [comment]
Is that on kci? Intel gfx, Opengl2?

**Comment by notmart** [comment]
on a system where everything is built from source doesn't seem to be reproducible, on a laptop that has plain kubuntu 15.04 (and ati drivers) the problem occurs.
trying to get oxygen for qt4 built on that system now

**Comment by notmart** [comment]
if i build oxygen qt4 from kde-workspace branch KDE/4.11 ,  i get correct shadows
@apachelogger , from what repository does come the sources of kde-style-oxygen-qt4?

**Comment by davidedmundson** [comment]
it should be kde/workspace/origin master (or 5.3) with -DUSE_QT4

**Comment by apachelogger** [comment]
we are using USE_KDE4 for some reason, reckon it matters?
http://anonscm.debian.org/cgit/pkg-kde/plasma/oxygen-qt4.git/tree/debian/rules

mind you it can only build with qt4 anyway because the build environment only has kdelibs4 available.

**Comment by notmart** [comment]
got built the version from oxygen.git with -DUSE_KDE4
popup menu shadows are fine as well.. perhaps the package of oxygen-qt4 is still a revision older than 6641eb4e4

**Comment by davidedmundson** [comment]
Got it (for Carbon at least, I imagine oxygen and potentially Breeze are the same)

please package qt4 versions with
libx11-xcb-dev

It's optional, but it's needed for the shadows on Qt4

The Qt5 cmake code warns, this doesn't.

**Comment by notmart** [comment]
breeze-qt4 on stock kubuntu doesn't seem to have shadows as well so i think has the same problem, yes

**Comment by apachelogger** [comment]
Ah, cool stuff. 

it would help a lot if it actually reported it as missing in the summary though :|
https://launchpadlibrarian.net/205812085/buildlog_ubuntu-vivid-amd64.oxygen-qt4_4%3A5.3.0%2Bgit20150507.0020%2B15.04-0_BUILDING.txt.gz

**Comment by apachelogger** [comment]
https://bugs.kde.org/show_bug.cgi?id=347419
https://bugs.kde.org/show_bug.cgi?id=347420

cmake output bugs FTR

**Comment by davidedmundson** [comment]
​Thanks

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-fixes/+sourcepub/5046159/+listing-archive-extra

**Comment by star-buck** [comment]
works!
