### ISSUE TITLE
[ksnapshot]: cannot invoke ksnapshot (with print key) while having context menu open

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#110]

**Comment by mgraesslin** [comment]
this is a restriction of X11 - while a context menu (grabbed keyboard) is open many features are not going to work. Among them are global shortcuts, screen locking, etc.

**Comment by star-buck** [comment]
I "know" those are all not "proper (X11)" programs, but for exmaple Libreoffice, Firefox, etc. have no problem invoking ksnapshot via Printkey with dropdown menu open...

**Comment by mgraesslin** [comment]
drop down menu != context menu. I just tried in iceweasel of Debian stable and there both context menus and drop down menus block global shortcuts from working.

**Comment by star-buck** [comment]
ksnapshot trigger via printkey works fine with firefox:
https://www.dropbox.com/s/hha5ozfotd1lry2/ff-ksnapshot.mkv?dl=0

**Comment by mgraesslin** [comment]
they seemed to have changed the context menu in a newer version, which seems to be no longer the GTK version which seems to work differently. It's possible that the menu is part of the web page now and thus doesn't break X11 mode.

Anyway: mood point. It's an X11 restriction.

**Comment by mgraesslin** [comment]
just watched the video again and noticed something interesting: once ksnapshot opens the menu closes and ksnapshot doesn't snapshot the menu. Looks like a Firefox regression to me (certainly not the intended behavior that the menu can get closed by other windows).

**Comment by star-buck** [comment]
yeah, interesting enough Libroffice does leave the menu open. This is nice if you for example make a tutorial and want to show where a menu entry is. Of course this can also be done with delay, it just might not be intuitive for some users...

**Comment by mgraesslin** [comment]
the new tool spectacle (which replaces ksnapshot) has a mode to snapshot context menus. One still cannot press print key while context menu is open, but one can work with a delay.

**Comment by star-buck** [comment]
lets wait for spectacle then, closing here.
