### ISSUE TITLE
[kdeglobals]: font settings are ignored

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#112]
settings set in XDG Dir's kdeglobals file and set Oxygen Sans for everything as default font

**Comment by notmart** [comment]
upstream fix in master in revision
http://quickgit.kde.org/?p=plasma-workspace.git&a=commit&h=842fb93d07c87b9ad4c2ad735f5601f0bde03017

**Comment by star-buck** [comment]
please mark ready for packaging when accepted, thanks.

**Comment by apachelogger** [comment]
I think Leszek already fixed this in
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-fixes/+sourcepub/5036523/+listing-archive-extra

do note that the current version actually is already ubuntu5:
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-fixes/+sourcepub/5038570/+listing-archive-extra

**Comment by llelectronics** [comment]
Yeah it is fixed there already

**Comment by star-buck** [comment]
works
