### ISSUE TITLE
[Kicker]: cannot "add to desktop" to folderview

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#116]
maybe its only in netrunner, since folderview has been scripted?
will test also on a fresh kci installation...

**Comment by eikehein** [comment]
Works here both with Fedora/git and the KCI ISO from Friday. Note you need to have widgets unlocked for the action to be shown.

**Comment by star-buck** [comment]
maybe it is because Leszek scripted it as Netrunner Desktop? So it is the default Folderview but named Netrunner Desktop? I am not sure if this nevertheless worked with Netrunner 15 though, will check...

**Comment by star-buck** [comment]
yeah, that seems to be an issue... I guess it cannot target the current containment if its not named Folderview? Or how does "add icon to desktop" determine to put the icon on the (actual active?) containment?

**Comment by eikehein** [comment]
It works like this: By default, "Add to Desktop" tries to create an instance of the Icon applet on whatever containment is on the desktop. Unless the containment's plugin name is org.kde.plasma.folder and its root item has an addLauncher method, then it calls that method instead (and Folder View implements that method as creating a symlink in the currently shown folder).

As I understand it Netrunner changes the name of Folder View to Netrunner Desktop in a .desktop file, but that shouldn't impact the plugin name. But maybe Leszek could comment here with details on what Netrunner does.

**Comment by star-buck** [comment]
@llelectronics : any hint for @eikehein ?

**Comment by llelectronics** [comment]
See here we only create a org.kde.plasma.folder activity with the name set to Netrunner Desktop: https://github.com/netrunner/netrunner-default-settings/blob/master/usr/share/netrunner-default-settings/plasma5-profile/plasma/shells/org.kde.plasma.desktop/contents/layout.js

I don't see how that affects this particular problem however.

**Comment by eikehein** [comment]
Yeah, I see no issue there. Is there an ISO somewhere i can try?

**Comment by llelectronics** [comment]
The last ISO is here: http://dev.netrunner.com/dev/netrunner-16-dvd-64bit-build2-150508-1416.iso
Though it should come with plasma 5.3 still. (not sure if plasma 5.4 from the title comes with an upgrade)

**Comment by star-buck** [comment]
The github title for this repo is iterating and only indicates that we are
in the post 5.3.0 area, moving towards 5.4.

**Comment by eikehein** [comment]
Ah crap, this is a genuine code bug - I forgot to remove a line of code when I refactored that code. It works here by luck, the scripting in Netrunner changes the instanciation order of some objects to things stop working. I'll fix it and link the patch here for you Leszek.

**Comment by eikehein** [comment]
Patch against plasma-desktop 5.3: http://commits.kde.org/plasma-desktop/b59ce5e838304213bcedf78f5d267b29d2874c4f

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-fixes/+sourcepub/5052853/+listing-archive-extra

**Comment by star-buck** [comment]
works!
