### ISSUE TITLE
[Notifications]: no start sound played

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#119]
even though a start sound for logging event has been set in kcm, no sound is played.
(I think we had this ticket opened in the past, but couldnt find it, so added this one)

**Comment by mck182** [comment]
There is an upstream bugreport here - https://bugs.kde.org/show_bug.cgi?id=335948

It was fixed, then reverted as on some systems it was starting PulseAudio during the login sequence and that has blocked the startup considerably.

It could be tried to invoke alsa directly for the playback (like using aplay) or maybe even just another thread/process which wouldn't block ksmserver in startup.

I was never able to reproduce the PulseAudio blocking though so I have no way for testing that. Can anybody please try uncommenting plasma-workspace/ksmserver/startup.cpp:402 and see if login blocks for you?

**Comment by mgraesslin** [comment]
could we start the notification from a thread? That way it would not matter if it blocks or not.

**Comment by mck182** [comment]
Probably, but I can't say if that fixes it because I don't have that blocking problem in the first place. So it'd be handy if someone could reproduce first.

I'll try to patch it blindly nevertheless.

**Comment by mck182** [comment]
http://commits.kde.org/plasma-workspace/b0fe26bfb314698693fcf011e59a28769bd9a437

**Comment by star-buck** [comment]
@apachelogger : please package here: 
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-updates

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-updates/+sourcepub/5068670/+listing-archive-extra

**Comment by star-buck** [comment]
works!! awesomeness :)

**Comment by star-buck** [comment]
too fast, seems it works only half-way:
After having updated and now trying to logout, kdeinit5 crashes with some "Phonon-Audiooutput" message, that might be related?
@mck182: any idea if this could cause logout problems, maybe it checks if to play a logout sound (which none is set, but still)?

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-updates/+sourcepub/5069883/+listing-archive-extra

**Comment by mck182** [comment]
For the record, this patch is now upstream (and extended a bit) at http://quickgit.kde.org/?p=plasma-workspace.git&a=commit&h=c445f99304bd0190a7a0b83e4700222132bc34d1

Plus there's an optimization that will not initialize the audio system at all if the sound is not enabled: http://quickgit.kde.org/?p=plasma-workspace.git&a=commit&h=2e60c27a85bd8c785db47be176f6b78a2d3c4ba8

I'd suggest to pick those two commits and have them replace the original patch on plasma-workspace.

**Comment by AJSlye** [comment]
This has been fixed in Plasma 5.4.
