### ISSUE TITLE
[samba-mounter]: user/password authentication only works after reboot

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#12]
* needs to add a second "/" after smb:/ , as smb:// does display resources in popup, while smb:/ doesnt (see dolphin)
* does not show folder icons (has generic icon instead)

![sambamounter-icons-missing](https://cloud.githubusercontent.com/assets/840070/5154040/33ca53ba-7246-11e4-8d1d-992be5310fab.png)

solved:
* popup: does not show content subfolders of a picked smb-resources (or too slow revealing them compared to under kde4.x)
* still displays "xyz on looking" when mount is saved, although "looking" has been finished and the mount is available

**Comment by star-buck** [comment]
crash fixed with qt5.4, icons still missing and authentication still needs a reboot to mount properly

**Comment by afiestas** [comment]
Update on this issue: https://git.reviewboard.kde.org/r/121447/

Waiting for ship it, I will backport it to the correct branch so we can get it to netrunner asap.

**Comment by afiestas** [comment]
Going to look at the reboot for authentication issue now.

**Comment by afiestas** [comment]
Another issue I am facing is that kio prompts for the user and password which causes 2 issues:
1-It blocks the GUI
2-It will force the user to introduce the credentials twice.

I am going to try to re-use the credentials so this way we get:
-Credentials tests by kio (so we don't have to do it)
-User only adds them once.

**Comment by star-buck** [comment]
thanks Alex for investigating, seems like a good improvement if fixed

**Comment by apachelogger** [comment]
@star-buck do we want to backport this to netrunner fixes ppa or only have it in the upcoming weekly iso?

**Comment by afiestas** [comment]
Things that have been fixed:
-missing incons
-triple slash :/// pending review: https://git.reviewboard.kde.org/r/122613/

Things coming next:
 - Share credentials with kio
 - Not having to re-mount when user/password added

My idea is to have for next friday the patch merged and sharing credentials with kio.

**Comment by star-buck** [comment]
@aleixpol : any update on these two:

 - Share credentials with kio
 - Not having to re-mount when user/password added

**Comment by aleixpol** [comment]
I'm sorry, I didn't realize I was assigned samba-mounter. I'll look into this tomorrow.

**Comment by aleixpol** [comment]
Submitted the reviews to be closed by Alex regarding samba-mounter usability, starting to look into the actual usability issues in this ticket.

For packaging purposes, these are the required fixes:
http://commits.kde.org/frameworkintegration/6788bacc9f8eb593e67e3264177d49d45eb1ddf4
http://commits.kde.org/kio/901871e7d4285afa4401d37fc7bb60956836a24e

**Comment by aleixpol** [comment]
Share credentials with KIO was just pushed.
http://commits.kde.org/scratch/afiestas/samba-mounter/a0d39d13892d5e79f53977cb9db20332abd352c0

Now looking into "Not having to re-mount when user/password added".

**Comment by aleixpol** [comment]
Hi Clemens,
Do you still have this video?
https://www.dropbox.com/s/qn67e6hxy2lms1r/samba-mounter-auth.mkv?dl=0

It might help me understand what's happening.

**Comment by star-buck** [comment]
Yes, here it is (not sure why the link actually changed): 
https://www.dropbox.com/s/lhtrasaujr9iji8/samba-mounter-auth.mkv?dl=0

**Comment by star-buck** [comment]
You see in the end, the password protected NAS share seems to get mounted, but shows empty content.
As soon as you reboot though, the mounted share shows actual content.

**Comment by aleixpol** [comment]
I just pushed the fix, it wasn't forwarding the username and password from the kcm but it was on load, that's why it was working afterwards.
I also added some ways to receive the errors we get from the KCM, so in case things don't work well, we'll get a little message. Useful to know how to react.

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-fixes/+sourcepub/5052868/+listing-archive-extra
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-fixes/+sourcepub/5052871/+listing-archive-extra

samba-mounter itself is in blue-shell-next as usual

**Comment by star-buck** [comment]
clsoing this now
