### ISSUE TITLE
[telepathy]: systray icon: right-click options not doing much

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#121]
https://www.dropbox.com/s/ghbmre0vr7adxg8/telepathy-systray-nothing-happens.mkv?dl=0

**Comment by mck182** [comment]
Is netrunner shipping kde-telepathy 15.04?

**Comment by star-buck** [comment]
i guess so, here is whats installed as packages:
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-official/+index?batch=75&memo=150&start=150

**Comment by mck182** [comment]
Ok so you need to remove kde-telepathy-legacy-presence-applet package, that's the applet you're using in the video and that is meant to be used with Plasma5+ktp0.9, it's not compatible with 15.04 (and the ktp-desktop-applets should be packaged in a way that it would remove the legacy one).

**Comment by star-buck** [comment]
okay, uninstalled this and as dependency kde-telepathy (also 0.9 version).

Then do I need to install anything else instead, because now there is no icon in systray, even if I start Telepathy from the Menu and minimize... (I looked under systray settings, and there is no option either).

**Comment by mck182** [comment]
It does require ktp-desktop-applets, which is in that packages list from above. Basically all of those ktp-* packages from that list should be installed and installed together.

**Comment by star-buck** [comment]
okay, that works fine now, thanks a lot!
