### ISSUE TITLE
[samba-mounter]: fails to mount on reboot when using wireless (as wireless connection gets established after whole desktop has been loaded already)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#123]
I remember this was working fine before (kde4)?
Maybe its now due to systemd in Kubuntu changing order of what starts when?

**Comment by aleixpol** [comment]
I don't see any code that would try to mount the code again when there's finally Internet connection.

**Comment by star-buck** [comment]
Exactly that!

**Comment by aleixpol** [comment]
Should work now.
In case it fails to mount, doesn't exit the process and waits until we're reported as online to try again.

http://commits.kde.org/scratch/afiestas/samba-mounter/35849c2a60e3f1bf25937810df65bb7b0e83a7c8

**Comment by star-buck** [comment]
@apachelogger : lets try in blueshellnext ppa or does it need some other package then for "testing": https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-testing ?
