### ISSUE TITLE
[undo]: first time undo deleting widgets works, second time after having really deleted the widget first time fails

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#124]
Example:
add Comic widget to desktop, remove: undo works.
now delete comic widget without undo, add comic widget again from widget menu and remove: undo pops up, but doesnt restore.

**Comment by konqoro** [comment]
Confirmed, also this bug has reappeared https://bugs.kde.org/show_bug.cgi?id=345149

**Comment by star-buck** [comment]
is that fixed?

**Comment by bhush9** [comment]
With steps provided I can not reproduce on latest git master.

**Comment by star-buck** [comment]
then fixed for now :)
