### ISSUE TITLE
[folderview]: selecting an icon while having "doubleclick" enabled, then right-clicking on it will show Folderview contextmenu, not icon specific contextmenu

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#126]
Selecting an icon with rubberband instead shows normal contextmenu for the filetype though.

**Comment by star-buck** [comment]
should have been right-clicking ON it, not in it...corrected the ticket title.

**Comment by eikehein** [comment]
I unfortunately can't reproduce this with the following steps:
- Left click an icon to select it
- Right click it

I get the right context menu here.

A video would be super helpful to see the steps!
