### ISSUE TITLE
[muon-updater]: show some sort of progress while updating

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#128]
while downloading and updating packages, show some sort of progress (either per package or total) instead of the back and forth idle bar.

**Comment by aleixpol** [comment]
On which distribution?

**Comment by star-buck** [comment]
why? isnt the frontend progress the same for arch, debian onhce packages can be updated with muon?

**Comment by aleixpol** [comment]
Yes, and it's the backend providing the progress. If the backend doesn't provide a progress, the frontend does the back-and-forth idle bar.

**Comment by star-buck** [comment]
the backend for arch is packagekit? 
since we unifiy on packagekit, can we get download/update progress from there or add it?

**Comment by aleixpol** [comment]
Yes. Will do.

**Comment by aleixpol** [comment]
I just looked it up and update has progress on my system. We're getting it right away from PackageKit, so it should be working.
Should I check why/whether it isn't working on Netrunner Rolling?

**Comment by star-buck** [comment]
please go ahead and check then.

**Comment by aleixpol** [comment]
I just created this issue at PackageKit, seems related: https://github.com/hughsie/PackageKit/issues/70

**Comment by star-buck** [comment]
closing this here
