### ISSUE TITLE
[ODROID]: plasma desktop issues

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#129]
this ticket is for keeping track of some plasma on odroid c1 issues that shadeslayer faces, any help or comments welcome.

**Comment by shadeslayer** [comment]
So we have a partially working image up, these are some of the issues I have at the moment with the image

* Kickoff doesn't load with 
```
Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml:35:34: Type FullRepresentation unavailable
file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/FullRepresentation.qml:296:5: Cannot assign object to list
```
However, starting it with plasmoidviewer and plasmawindowed works.


* Systemsettings aborts on startup, however (this)[http://paste.debian.net/283011] seems to make it work
