### ISSUE TITLE
[ODROID]: Systemsettings aborts on startup

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#131]
Systemsettings aborts on startup, however [this](http://paste.debian.net/283011) seems to make it work

**Comment by star-buck** [comment]
the actual error message is:
'''
odroid@OdroidC1:~$ systemsettings5
kf5.kiconthemes: "Theme tree: (Oxygen)"
QWidget: Cannot create a QWidget without QApplication
Aborted
'''

**Comment by shadeslayer** [comment]
Both Aleix and Martin G. have mentioned that this patch is nonsense, so I'm not sure what the correct way of fixing this is.

**Comment by star-buck** [comment]
What might be causing the above error message?

**Comment by aleixpol** [comment]
@shadeslayer I didn't say it's nonsense, I said that it will break other things (i.e. dbus integration).

Actually, looking at the system with Rohan last week, it even looked like dbus integration is broken in other places as well, but those didn't end with a crash, therefore being less obvious problems.

**Comment by shadeslayer** [comment]
Actually, Plasma also crashes when one runs qdbus org.kde.plasmashell ... I just don't think the backtrace was particularly useful though.
