### ISSUE TITLE
[Desktop Settings]: "Tweaks" dialog has white font text

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#135]
Seen here: https://www.youtube.com/watch?v=--lXdTLjhH8&feature=player_detailpage#t=2495

All other dialog pages in this Settings have black font.

**Comment by bhush9** [comment]
Fixed in : http://quickgit.kde.org/?p=plasma-desktop.git&a=commit&h=5f807ffcac9ed193c3efd1595aaf061e18e2ae4e

**Comment by star-buck** [comment]
lets always add the info which official version (plasma, frameworks, qt, or other part) this bug should be fixed in. 
I assume Plasma 5.4.0 fixed it, as the font seems fixed there, so closing.
