### ISSUE TITLE
[ksysguard]: freezes when started

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#137]
ksysguard window loads and comes up, then freezes immediatly. One can only terminate the window...
terminal output is:
"Trying to convert empty KLocalizedString to QString."

**Comment by davidedmundson** [comment]
That warning is mostly a non issue.

Is this freeze on the latest CI ISO?

**Comment by star-buck** [comment]
thats what I'm waiting for: next KCI on friday to test :)

**Comment by star-buck** [comment]
seems not have occured anymore, closing this.
