### ISSUE TITLE
[kci]: black screen with mouse-cursor on intel i915

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#138]
tty1 has this error:
drm:intel_set_cpu_fifo_underrun_reporting [i915]

**Comment by star-buck** [comment]
mouse can stil be moved, but nothing else (e.g. krunner) seems to work

**Comment by bhush9** [comment]
drm:intel_set_cpu_fifo_underrun_reporting [i915]

error is irrelevant.. I see this even with normal operation. Probably ~/.xseesior-errors will help
