### ISSUE TITLE
[systray]: sometimes there is a gap between icons

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#140]
![systray-gap](https://cloud.githubusercontent.com/assets/840070/9154787/c3d8c564-3ea0-11e5-89cb-a801aad0680d.png)

**Comment by davidedmundson** [comment]
and that gap is.... plasma-pa.

Got a bug report matching this today, and I can't see plasma-pa elsewhere in your screenshot
https://bugs.kde.org/show_bug.cgi?id=351427#c1

**Comment by davidedmundson** [comment]
spent most the afternoon on this. Not really got anywhere, but probably now in the best position in BS to fix it.

At the very least I found a tonne of optimisisations to do having stared at so much of the code.

**Comment by davidedmundson** [comment]
We now have an open bug report in Qt of the problem we're hitting:
https://bugreports.qt.io/browse/QTBUG-48870

ideally we need a workaround anyway, but it's good that they've acknowledged the root problem

**Comment by star-buck** [comment]
still happens in kubuntu with plasma 5.4.3

**Comment by davidedmundson** [comment]
There's now a fix in review in Qt: https://codereview.qt-project.org/#/c/141620/

**Comment by star-buck** [comment]
please write which qt version would fix this, otherwise we need a workaround for the time being as distros might not ship always the latest qt with the already released plasma.

**Comment by llelectronics** [comment]
I researched that problem regarding plasma-pa icon and found that solution. So far after all tests done here I don't have that problem anymore with Plasma 5.5 and Qt 5.5.1 (with the patches from the Xenial Ubuntu Repo): https://bugs.kde.org/show_bug.cgi?id=352055#c37

**Comment by davidedmundson** [comment]
That workaround is now in Plasma 5.5.1

**Comment by star-buck** [comment]
if this has been solved, please mark it green :)

**Comment by star-buck** [comment]
@davidedmundson : Can we close this ticket for good?

**Comment by davidedmundson** [comment]
The real fix is in Qt5.6 (out next month or so). 

A hopeful workaround is in now.

The workaround is, a workaround. It might have fixed it for you, it might not.  I don't want to promise anything regarding that.

There's not much else I can do though so we may as well close it.
