### ISSUE TITLE
[kci]: sudo has wrong uid

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#141]
![sudo](https://cloud.githubusercontent.com/assets/840070/9154791/f5e0c6e2-3ea0-11e5-99d8-2210f58e7ded.png)

**Comment by davidedmundson** [comment]
Not just that file, half of /etc is. Groups are messed up too

drwxr-xr-x  3 root   root        4096 Aug  7 11:20 acpi
-rw-r--r--  1 100000 bluetooth   2981 May 15 12:33 adduser.conf
drwxr-xr-x  2 root   root        4096 Aug  7 11:20 akonadi
drwxr-xr-x  2 100000 bluetooth   4096 Aug 10 00:27 alternatives
-rw-r--r--  1 root   root         401 Dec 28  2014 anacrontab
