### ISSUE TITLE
[lockscreen]: unlock failed

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#142]

**Comment by davidedmundson** [comment]
failed where?

**Comment by star-buck** [comment]
simply unlocking doesnt accept the password... i had to hard reboot... kci20150807 could be also sudo or uid user wrong...

**Comment by llelectronics** [comment]
Hmm maybe it showing the password prompt but isn't actually locked. So pressing unlock without a password works.
I saw that once on one of my machines with an older Plasma 5.3 build though

**Comment by star-buck** [comment]
no, unlocking without password doesnt work either.
Further, even DISABLING the lockscreen in kcm doesnt help, the lockscreen still comes up even though it is UNTICKED.

**Comment by bhush9** [comment]
What if you do ```sudo loginctl unlock-session``` from the tty when this happens?

**Comment by davidedmundson** [comment]
Urgh, I was just able to lock the live session which should be impossible.

**Comment by davidedmundson** [comment]
Notes from my investigation so I remember tomorrow morning.

kcheckpass is continually returning "auth failed" even when invoked standalone or forced to use the same service as sddm which we know is working.

It is using PAM properly, going through common-session 

Logs below from auth.log show pam is then saying we don't have a valid user... despite clearly knowing it.

Aug 10 00:36:27 david-VirtualBox unix_chkpwd[1825]: check pass; user unknown
Aug 10 00:36:27 david-VirtualBox unix_chkpwd[1825]: password check failed for user (david)
Aug 10 00:36:27 david-VirtualBox kcheckpass[1824]: pam_unix(common-auth:auth): authentication failure; logname=david uid=1000 euid=1000 tty=/dev/pts/2 ruser= rhost=  user=david
Aug 10 00:36:27 david-VirtualBox kcheckpass[1824]: Authentication failure for david (invoked by uid 1000)

Though clearly kcheckpass is sending the right user as that's in the logs.

It seems it only affects the ISO; Kubuntu 15.04 + my builds of Plasma are fine.

**Comment by davidedmundson** [comment]
FYI, I'm leaving this until the rest of the permissions thing in https://github.com/blue-systems/plasma-5.4/issues/141 is fixed, as I think it's likely they're related.

**Comment by davidedmundson** [comment]
Seems fixed in new image

**Comment by star-buck** [comment]
seems fixed, closing.
