### ISSUE TITLE
[sambamounter]: add second "/" in front of smb:/ default

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#146]
result:
![sambamounter-doubleslash](https://cloud.githubusercontent.com/assets/840070/9489477/a7310d74-4be1-11e5-9019-ec326692a47d.png)

**Comment by star-buck** [comment]
hi Aleix, can you please add the second slash, so we can update the package?

**Comment by aleixpol** [comment]
Done.
http://commits.kde.org/scratch/afiestas/samba-mounter/f03b6e790e16e282410e0000b9434fbb9a34fbf1
