### ISSUE TITLE
[discover]: no "install" button on single page, but in list

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#147]
https://www.dropbox.com/s/tsu26yqp1c14uun/discover-missing-install.mkv?dl=0

**Comment by star-buck** [comment]
also note in that video, I can install any software without need for password confirmation (is that behavior correct for discover?)

**Comment by aleixpol** [comment]
I reproduced it, I'm looking into it.

**Comment by aleixpol** [comment]
Fixed: http://commits.kde.org/muon/f4009a08992d440b4aac60514e201e33e392fe47

**Comment by aleixpol** [comment]
Regarding the auth, I think it's ok.

It's up to PackageKit to request it anyway.
