### ISSUE TITLE
[kamoso]: cannot open saved jpg file with gwenview

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#149]
pictures taken and saved with kamoso cannot be opened with gwenview... other "normal" jpgs open fine.

**Comment by aleixpol** [comment]
Works here, I need more information to reproduce. where did you test it?
http://imgur.com/rcuVxh5

starbuck:
`manjaro with official plasma 5.4.1... will try again with next install and give extra attention to it, maybe foldernames didnt initialize properly....`

**Comment by star-buck** [comment]
manjaro plasma 5.4.1... took a screenshot of the error in gwenview:

**Comment by AJSlye** [comment]
This appears to be a metadata issue with gwenview, all other viewers besides gwenview can open the pictures produced by Kamoso.

I suggest this is a bug in gwenview not Kamoso.
