### ISSUE TITLE
[kamoso]: save videos in "video" folder instead of pictures

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#151]

**Comment by aleixpol** [comment]
Works here, I need more information to reproduce. where did you test it?
http://imgur.com/rcuVxh5

**Comment by star-buck** [comment]
manjaro with official plasma 5.4.1... will try again with next install and give extra attention to it, maybe foldernames didnt initialize properly....

**Comment by aleixpol** [comment]
I replied to the wrong issue. This one isn't solved yet.

At the moment it was up to the user to configure this, I guess it doesn't make sense after all...

**Comment by star-buck** [comment]
okay, i just also tried it again, confirming that the movie lands in "pcitures" (there is even a notification reporting .mkv video-file copying to Pictures has been finished :)

**Comment by aleixpol** [comment]
Fixed: http://commits.kde.org/kamoso/1ee13f8256be18eb715afdb85a91f389c1b478c1

**Comment by star-buck** [comment]
is that in kamoso 3?

**Comment by aleixpol** [comment]
Yes, will be in 3.1.

**Comment by aleixpol** [comment]
Fixed in the last 3.1.0 release: http://download.kde.org/stable/kamoso/3.1/src/kamoso-3.1.0.tar.xz.mirrorlist

**Comment by star-buck** [comment]
works
