### ISSUE TITLE
[freeze]: while opening tasks, sometimes loading task gets stuck in (ExpandingIcons-)Taskmanager and the whole system freezes totally, requiring hard-reboot

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#153]
The taskmanager (EITM in this case) seems stuck and the app window never materializes... this could be a coincidence with EITM though (Does anyone had a freeze happen with task stuck and window not appearing with normal Taskmanager or Icononly?). 
It also happens with every app now and then, qt and non-qt.
Happenend on any gfx, intel, ati, even odroid (where it seems to happen much more frequent though, maybe thats an indicator of something on a weak cpu race condition?).
So it looks like a plasma/system-internal bug.

**Comment by shadeslayer** [comment]
Maybe related, but @eikehein asked me to update EITM last week, but since we've been having issues for quite some time, this might not actually fix anything? Still worth a try.

**Comment by star-buck** [comment]
i wonder if there is ever reported or known to happened a similar case of a freeze recently with anything else but EITM...

**Comment by shadeslayer** [comment]
You can test the new binary by downloading it from here http://dci.pangea.pub/job/extras/job/expanding-icons-taskmanager_binary_unstable/arch=armhf/lastSuccessfulBuild/artifact/build/binary/expanding-icons-taskmanager_1+git20150924.1732+9-0_armhf.deb

**Comment by star-buck** [comment]
Thanks.
Lets also put this in a new IMG for the weekend to see how it goes right from the start.

**Comment by star-buck** [comment]
seems not to happen with 5.5, closing for now
