### ISSUE TITLE
[discover]: replace "red arrow" with green circle + arrow inside (similar to widget explorer for widgets installed with number inside)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#155]
reason: red always signals something is "wrong" instead of "okay"

**Comment by star-buck** [comment]
reason: red always signals something is "wrong" instead of "okay"

**Comment by aleixpol** [comment]
This is solved in a different way on the redesigned version:
https://community.kde.org/KDE_Visual_Design_Group/Muon_Discover
https://www.youtube.com/watch?v=8-W4UdkiBcc
https://forum.kde.org/viewtopic.php?f=285&t=121810&start=90#p342880

It should be in in the next Plasma version.
