### ISSUE TITLE
[discover]: make category panels on frontpage (and elsewhere) same height regardless of how many textrows the categories take

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#156]
It looks a bit unprofessional having the category panels not the same size heightwise:
![discover-frontpage](https://cloud.githubusercontent.com/assets/840070/10267267/c20dbc5e-6a7d-11e5-84ef-2eb2b8255f64.png)

**Comment by aleixpol** [comment]
This shouldn't be a problem as of the redesign. I'll leave the issue opened until it's merged.
