### ISSUE TITLE
[window deco kcm]: cannot click on settings icon while entry is selected

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#159]
demonstration as it happened here:
https://www.youtube.com/watch?v=Y_CmBGOxbGQ&feature=player_detailpage#t=597
Plasma 5.4.1

**Comment by mgraesslin** [comment]
I'm not able to reproduce. Sorry I am not able to derive the right click sequence from that video.

**Comment by star-buck** [comment]
yeah, in kci the behaviour seems fine.
in kci there seems another bug reproducable though: clicking on the settings icon of Plastik crashes the settings/kcm.

**Comment by star-buck** [comment]
closing this for now
