### ISSUE TITLE
[kate]: minimap hardly useable with breeze widget themeing

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#160]

**Comment by aleixpol** [comment]
Can you pass a screenshot? I'll meet the Kate guys tomorrow, maybe they can take a look!

**Comment by star-buck** [comment]
in latest kci the minimap appears fine.
On Netrunner, the minimap appears floating around, not sure if its the different colors as I also use Breeze window deco with same options.
Will make a screenshot next time i boot into rolling, currently testing kci as only partition due to wiping my harddrive :/

**Comment by eikehein** [comment]
If you can take one *right now*, I'm in a room with eight Kate hackers as I write this ...

**Comment by star-buck** [comment]
![kate-minimap](https://cloud.githubusercontent.com/assets/840070/10351210/90a8c726-6d48-11e5-8ba4-dd6fa7e53d48.png)
current manjaro with Plasma 5.4.1 and their themeing. although netrunner uses different themeing, its the same effect.

**Comment by eikehein** [comment]
Ok, the developer of the minimap plugin just told me it's fixed in master as of recently, but in your version you can supposedly work around it by enabling the "Scrollbar marks" checkbox on the Borders config page :)

**Comment by AJSlye** [comment]
This was fixed in KDE applications 15.08.2, which hit the Manjaro stable branch on Monday the 19th.

**Comment by star-buck** [comment]
solved
