### ISSUE TITLE
[gwenview]: select "save as": only change extension, keep original filename

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#162]
when selecting "save as" and choosing a different filetype extension, gwenview should always keep the name and only suggest extension, example:
Open A.png with gwenview and "save as" jpg, it suggests A.jpg.
After closing gwenview, then opening a second file like B.png, "save as" and choosing jpg switches also name to A.jpg (expected would be B.jpg).

This may be related to the alphabetical last item found with that extension in saving dialog list:
https://www.dropbox.com/s/e0y9os6nhxkpag0/gwenview.mkv?dl=0

**Comment by davidedmundson** [comment]
Fixed, on review: https://git.reviewboard.kde.org/r/126085/

**Comment by davidedmundson** [comment]
FYI, this is now released in newest frameworks.
