### ISSUE TITLE
[desktop]: adnd doesnt work properly anymore, e.g. on comics widget

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#164]
pressing on a comics widget sometimes gets into edit mode revealing the handle, but then never leaves it (handle stays always visible).

**Comment by eikehein** [comment]
Clemens, can you record a video of this so I have more to go on? I can't reproduce it on my system, the handle properly disappears soon after leaving the widget. A video might give me a better clue.

**Comment by star-buck** [comment]
Please try Kubuntu or Netrunner 17: http://www.netrunner.com/download-id/4232/
It seems the handle doesnt properly go back also with any other widget.
The strange thing is that it worked with previously Netrunner 16 just fine.

**Comment by eikehein** [comment]
On the ISO ADND seems to be completely broken - not only the handle doesn't disappear, dragging from outside the handle also doesn't work. It's working in master though. I notice Netrunner still ships the 5.4.2 release and not 5.4.3, I'll check tomorrow which version range this problem might affect.

**Comment by eikehein** [comment]
It's broken specifically with the patched Netrunner Desktop containment, it's fine with the default one.

**Comment by eikehein** [comment]
Discussed fix with Leszek, should hopefully get fixed with package update now.

**Comment by llelectronics** [comment]
Packaged, tested and released to repo.

**Comment by AJSlye** [comment]
Can we get the same commits to the 2015.10 branch, or can we get the same commits to the 2015.10?

**Comment by star-buck** [comment]
still not working in latest plasma 5.5.0 / Qt5.5.1.

**Comment by AJSlye** [comment]
This seems to be working for me, albeit you have to click and hold near the
border of the widget for the tools to appear. However, they do seem to
disappear as they are supposed to once you click away from the widget
though.

**Comment by eikehein** [comment]
It's working fine for me with the Desktop / Folder View containments. Please test with those -- if it works with them but not with Netrunner Desktop, it's the fork that screwed up. Note that the patches to fix it the last time were for 5.4 and aren't needed for 5.5.

**Comment by AJSlye** [comment]
If you look at the 2015.10 branch those patches never we're applied there.
The desktop-containment 5.5.0 package in the netreunner-testing repository
was built against this branch and was used on the dev3 ISO. I did however
build the desktop-containment 5.4.3 package that's in the main netrunner
repository against the netrunner-17 branch since plasma 5.4.3 is what is
currently in the Manjaro stable repositories and needs those patches.

**Comment by eikehein** [comment]
I don't really understand any of this branch and version business so I can't comment on it. What I did originally was write a bash script that makes a git clone of the containment code and modifies it to spit out a packagable Netrunner Desktop containment, and advice that it should be re-run with every Plasma release / modified to check out the right branch and or tag. So it needs to be ensured that the Netrunner Desktop code you're shipping with Plasma 5.5 is the result of a run of that script using the 5.5 branch code.

**Comment by llelectronics** [comment]
@eikehein the script is good but we created a source repo with two different codebases as running the script everytime does not work (urls to patches and patches itself get obsolete). 
@AJSlye is the current 2015.10 branch the code you are using for 5.5 ? 
Like eike mentioned it maybe needs updating. I will take a look at it for Plasma 5.5

**Comment by eikehein** [comment]
> running the script everytime does not work (urls to patches and patches itself get obsolete). 

I was making the script because nobody wanted to maintain a repo fork this time and adviced to rehost the patches out of the pastebin~

**Comment by llelectronics** [comment]
@eikehein The initial version had c++ patches not only a simple qml based fork. (that was the initial reason I did not want to maintain that code) 
But in general either solutions aren't timesavers if the patch files don't work anymore as the files they should patch change :P

**Comment by llelectronics** [comment]
Should be fixed now in its own plasma5.5 branch

**Comment by star-buck** [comment]
works again now.
