### ISSUE TITLE
[kamoso]: save file with"date-timestamp".jpg instead of just picture1, picture2...

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#165]
see cheese: "yyyy-mm-dd_hh-mm-ss"

**Comment by aleixpol** [comment]
The current format is `picture_24202015_142032.jpg`. Maybe I should just release a new version.

**Comment by aleixpol** [comment]
Fixed in the last 3.1.0 release: http://download.kde.org/stable/kamoso/3.1/src/kamoso-3.1.0.tar.xz.mirrorlist

**Comment by star-buck** [comment]
works
