### ISSUE TITLE
Crash changing widget style qtcurve -> breeze

### ISSUE THREAD

**Issue by davidedmundson** [blue-systems/plasma-5.4#71]
system settings is also crashing when:

    setting "widget theme" from qtcurve to breeze, then "apply"

but switching from breeze to qtcurve works without crash

**Comment by davidedmundson** [comment]
Moving to a new bug report, because I lost it in the middle of that other one.

Backtrace
https://paste.kde.org/pvhhfielh

**Comment by davidedmundson** [comment]
Fix for breeze.
https://paste.kde.org/psv1h3gdw

Will put on reviewboard and get merged into Plasma 5.2 also

**Comment by apachelogger** [comment]
doesn't apply against 5.2.0

**Comment by davidedmundson** [comment]
commit 92aa888ea05267ed261ee3f876d3c728058533db on Plasma/5.2 branch

**Comment by apachelogger** [comment]
waiting for leszek to fix his breeze upload in fixes ppa

**Comment by apachelogger** [comment]
This should be fixed in Netrunner 16 (with with shipping Plasma 5.3)

**Comment by star-buck** [comment]
seems fixed!
