### ISSUE TITLE
[ubiquity crash]: German-Swiss causes ubiquity-141-error crash

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#72]
ubi-console-setup failed with exit code 141.
 see also:
 https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1182784
 https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1373033
 http://forum.ubuntuusers.de/topic/vivid-vervet-15-04-allgemeine-diskussion-zur-e/5/
 /var/log/syslog (at very bootm around 15:45:59): http://netrunnerlinux.com/netrunner-15/syslog.txt
 possible solution: https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1182784/comments/60

**Comment by star-buck** [comment]
ISO for testing is here: http://dev.netrunner-os.com/dev/netrunner-15-dvd-64bit-build7g.iso

**Comment by star-buck** [comment]
So the interesting thing is, that once you initialize your language to "German" via the first page of ubiquity, the language check for available layout fails (probably due to being localized to a non-english version)? 
In system settings keyboard kcm, there is also a non-defined (empty) layout set:
![empty-layout](https://cloud.githubusercontent.com/assets/840070/6199109/1626cd0e-b42f-11e4-9f13-bc8423422e78.png)

Under "Limit selection by language" there is only "German, Swiss" (is that a combined entry for German and Swiss or a selective one saying only "Swiss German"?), so once you pick that there is no German layout available anymore.
If you dont use the above Filter and go to the dropdown "Layout", there is a proper German layout available. I assume somehow this is also a factor of why ubiquity fails?

**Comment by star-buck** [comment]
Latest KCI ISO is installing fine with German selected and German keybaords:
http://files.kde.org/snapshots/unstable-i386-latest.iso.mirrorlist

Anything different from netrunner ISO with regards to ubiquity or missing packages?

**Comment by jriddell** [comment]
The workaround is just not to select it from "limit by language" and select it straight from Layout where both German and German (Switzerland) should be available.

The list of languages comes from /usr/share/xml/iso-codes/iso_639_3.xml which does have German in it but presuambly that list gets filtered somehow and misses out German.

**Comment by jriddell** [comment]
Looks like the filtering is in xkb_rules.h  / .cpp

**Comment by jriddell** [comment]
You can add in languages.insert("deu"); to AddLayoutDialog::AddLayoutDialog() in kcm_add_layout_dialog.cpp and it'll appear in the combobox but it crashes on selection so I guess it's missing knowing what keyboards use German.

**Comment by jriddell** [comment]
Can you describe your installer problem? I can't currently recreate it.

Reported the keyboard kcm issue upstream
https://bugs.kde.org/show_bug.cgi?id=345697

**Comment by jriddell** [comment]
Tried today on both Kubuntu daily and KCI image from last friday and couldn't create a problem installing in German selecting any keyboard. Let me know if it's still a problem.

**Comment by star-buck** [comment]
crashes again due to Switzerland conflict:
![ubiquity-crash](https://cloud.githubusercontent.com/assets/840070/6987107/531be2ae-da44-11e4-856b-91ed52f6f001.png)
Pick "Deutsch" from the start, then everything is matched with Deutsch like Keyboard, then try to change it to Switzerland.

**Comment by star-buck** [comment]
if you are on it and these two likely seem related:
please change to have German back as normal in the kcm filterlist as wrongly shown here: https://github.com/blue-systems/plasma-5.3/issues/72#issuecomment-74349887

**Comment by jriddell** [comment]
OK worked out how to recreate it, thanks for your patience. It's the lang-standing problem in bug
https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1182784

**Comment by jriddell** [comment]
in 2.21.21 it'll give you a warning that it's broken and needs set by hand after install rather than just crash.  A proper fix would be to work out why console-setup misses that translation but that's beyond my knowledge without some more time.

**Comment by star-buck** [comment]
will close this for now, not sure if this is properly fixed.

**Comment by star-buck** [comment]
still reported as crashing due to Switzerland: 
http://forums.netrunner.com/showthread.php?tid=17611&pid=27353#pid27353
