### ISSUE TITLE
[plasma-volume-control]: needs kcm settings

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#79]
Volume kontrol kcm under system settings seems empty (not showing any devices)

**Comment by apachelogger** [comment]
there's nothing there yet

**Comment by star-buck** [comment]
@apachelogger : can you work on the settings module after the kubuntu release tomorrow, or may someone else get this done before netrunner vivid comes out?

**Comment by apachelogger** [comment]
@star-buck I already added kcm content earlier last week

**Comment by star-buck** [comment]
@apachelogger : does it automatically come with package plasma-volume-control or needs another package?

**Comment by apachelogger** [comment]
@star-buck It does come with the package. We are moving the package to KCI though, and since KCI isos are rolling off of the stable branches until plasma 5.3 comes out and the volume thing has no stable branch it won't be installable unless one adds the unstable PPA manually.

**Comment by star-buck** [comment]
kcm is still not showing up... how to install from blueshellnext ppa?

**Comment by apachelogger** [comment]
@star-buck the package is now covered by KCI so you can install it on the ISO without the additional ppa.

sudo apt install plasma-volume-control && kbuildsycoca5  && systemsettings5

**Comment by star-buck** [comment]
seems fine now.
