### ISSUE TITLE
[qml]: mouse-wheel vertical scrolling is slow compared to "normal" applications

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#87]
compare dolphin (/usr/share) or kate vs. muon discover (Multimedia)

**Comment by aleixpol** [comment]
I've been playing around with it. I agree it does feel very different. Looking into it.

**Comment by aleixpol** [comment]
Made a change in Qt, waiting for feedback.
https://codereview.qt-project.org/#/c/109615/

**Comment by star-buck** [comment]
Is this fixed?

**Comment by aleixpol** [comment]
It's fixed, but the patch is not yet in Qt. I added some new people to see if I get to find somebody to care about it.

**Comment by star-buck** [comment]
another simple way to test is "add widget"

**Comment by aleixpol** [comment]
The patch has been cherry-picked and will be in Qt 5.5.
https://codereview.qt-project.org/#/c/109615/

**Comment by star-buck** [comment]
still not done with qt5.5, i opened another ticket for plasma5.5.
