### ISSUE TITLE
[Save-as Dialog]: e.g. Ksnapshot requires double-click for browsing file dialog while single-click is default

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#93]

**Comment by eikehein** [comment]
My guess: Still KDE 4 version of KSnapshot + click setting not synced back to 4.

**Comment by davidedmundson** [comment]
Ksnapshot 4- can reproduce this problem
Open dialog on Okular4 - reproduces the problem too
KSnapshot 5 - works as expected

which matches your theory, but:
The setting is synced back 

cat ~/.kde4/share/config/kdeglobals
[KDE]
SingleClick=true

Dolphin 4 is honouring the setting for the main view

---

So it's just confusing. Will investigate Monday.

**Comment by davidedmundson** [comment]
Found it!

Whether to activate on single click comes from the style; Breeze or Oxygen.
(kdelibs4 also had a method in kglobalsettings, but that's only used in half the places. Just to make things harder to find.)

The code was moved in the KF5 porting of the themes, to a base class called kstyle. However that means when building the KDE4 versions of these it simply doesn't work, and follows whatever QCommonStyle does.

It also implies the following other things are broken:
  - SH_DialogButtonBox_ButtonsHaveIcons
 - Toolbarstyle
 - Whether widgets animate

will fix all the things.

**Comment by davidedmundson** [comment]
https://git.reviewboard.kde.org/r/123188/

will need doing for Oxygen too, but should be a 5 minute copy and paste when this is accepted.

**Comment by davidedmundson** [comment]
All pushed, should be ready for next week's ISO and Plasma 5.3

**Comment by star-buck** [comment]
Double or single click behaviour is dependent on Widget Style Themeing??
I begun testing netrunner 16 build0, which is based on official kubuntu + kci ppa repos, but this seems still not fixed with oxygen widget style.
What files does this require in which version or with which patch?

**Comment by davidedmundson** [comment]
>Double or single click behaviour is dependent on Widget Style Themeing??

Yeah. From Qt's POV styles are for windows/os x.. we just use it for different UIs too


As for the problem, my patch misses something important, fixing now. Sorry :(

**Comment by star-buck** [comment]
No need to be sorry :)

**Comment by davidedmundson** [comment]
Apply these.

aa34eb031e205c6b21bcfe055523ca9be95b8dac  - breeze
b8f9cecab36094a04f2973e2770e865703f770e1 - oxygen

You'd be sorry if you saw what's in this patch, I got so distracted noticing 3 other things were missing, I forgot to actually implement the thing we were fixing in the first place in the final tided up patch. Then I must have run ksnapshot5 when I was testing.

**Comment by star-buck** [comment]
@davidedmundson : would the reverse also be solved with this patch?
Currently, I seem to be able to set dolphin4 to doubleclick, but systemsettings5 still then triggers on singleclick...

**Comment by davidedmundson** [comment]
Oxygen works; (note you need to manually install oxygen-style-qt4 as that's not part of the ISO apparently)

In Breeze the fix from before didn't get merged back into master from when I fixed it for 5.3, so it was broken again; that's now merged into 5.4 and onwards, so this is all fixed now, but needs a rebuild.
